#!/bin/sh 

wallpaper="$HOME/Pictures/wp.png"

sxhkd &
xrandr --auto &
nm-applet &
blueman-tray &
xrdb ~/.Xresources &
compton --vsync opengl-swc --paint-on-overlay --config ~/.config/compton/compton.conf &
xinput --set-prop "FocalTechPS/2 FocalTech Touchpad" "libinput Tapping Enabled" 1 &
xinput --set-prop "FocalTechPS/2 FocalTech Touchpad" "libinput Natural Scrolling Enabled" 1 &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -g 1366x768+0+0
bspc config border_width         0
bspc config window_gap 		 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 	 24
bspc config focus_follows_pointer true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^1'
bspc rule -a spotify desktop='^7'
bspc rule -a kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a telegram-desktop state=floating follow=on

feh --no-fehbg --bg-fill $wallpaper
xsetroot -cursor_name left_ptr &
pgrep bspswallow || bspswallow &

# polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar example
# !polybar

# Win + space language layout
setxkbmap -model pc105 -layout pl,ru -variant qwerty -option grp:win_space_toggle

# touchpad
flameshot
