#!/bin/zsh

export INSTALL_UDEV_RULES=1
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="urxvt"
export BROWSER="brave-browser"

# ~/ clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZSH="${XDG_CONFIG_HOME:-$HOME/.config}/oh-my-zsh"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export WINEPREFIX="${XDG_CONFIG_HOME:-$HOME/.local/share}/wineprefixes/default"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export GTK_RC_FILES="${xdg_config_home:-$home/.config}/gtk-1.0/gtkrc"
export CUDA_CACHE_PATH="${XDG_CACHE_HOME:-$HOME/.cache}/nv"
export LESSHISTFILE="-"
export LESSKEY="${xdg_config_home:-$HOME/.config}/less/lesskey"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"
export ASPELL_CONF "per-conf ${XDG_CONFIG_HOME:-$HOME/.config}/aspell/aspell.conf; personal ${XDG_CONFIG_HOME:-$HOME/.config}/aspell/en.pws; repl ${XDG_CONFIG_HOME:-$HOME/.config}/aspell/en.prepl"

